services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init: 
    build: .
    container_name: airflow_init 
    depends_on: 
      - postgres 
    environment: 
      AIRFLOW__CORE__EXECUTOR: LocalExecutor 
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow 
      AIRFLOW__CORE__LOAD_EXAMPLES: "false" 
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow/source
      PYSPARK_PYTHON: python
      PYSPARK_DRIVER_PYTHON: python
    volumes: 
      - ./.env:/opt/airflow/.env
      - ./source:/opt/airflow/source 
      - ./source/dataops:/opt/airflow/dags 
      - ./data:/opt/airflow/data 
    command: > 
      bash -c "airflow db init && airflow users create --username airflow --password airflow --firstname Airflow --lastname Admin --role Admin --email airflow@example.com"

  airflow-webserver:
    build: .
    container_name: airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow/source
      PYSPARK_PYTHON: python
      PYSPARK_DRIVER_PYTHON: python
    volumes:
      - ./.env:/opt/airflow/.env
      - ./source:/opt/airflow/source
      - ./source/dataops:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow/source
      PYSPARK_PYTHON: python
      PYSPARK_DRIVER_PYTHON: python
    volumes:
      - ./.env:/opt/airflow/.env
      - ./source:/opt/airflow/source
      - ./source/dataops:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: scheduler

volumes:
  postgres-db-volume: