FROM node:20-alpine

WORKDIR /app/source/devops/frontend

COPY source/devops/frontend/package*.json ./
RUN npm install

COPY source/devops/frontend ./

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]